version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
      - ${LOCAL_IP}:${DK_SERVER_PORT}:80
    depends_on:
      - mysql
      - redis
    links:
      - mysql
    volumes:
      - ${LOCAL_DEV_DIR}:/var/www
  mysql:
    build: ./DockerFiles/Mysql
    ports:
      - ${LOCAL_IP}:3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis

